#pragma config(Sensor, dgtl1,  bumpSwitchFront, sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitchBack, sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           sweepMotor,    tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

  Straight, Switch, Turn Left
  Straight, Switch, Sweep Arm
  Straight, Switch, Turn Right
  Straight, Switch, Turn Right
  Straight, Switch, Turn Right
  Straight, Switch, Sweep Arm
  Straight, Switch, Turn Left
  Straight, Switch, Turn Left
  Straight, Switch, Turn Right
  Straight, Switch, Turn Right
  Straight, Switch, Turn Right
  Straight, Switch, Turn Right
  Straight, Switch, Sweep Arm
  Straight, Switch, Turn Right
  Straight, Switch, Stop

*/

task main()
{                                     //Program begins, insert code within curly braces
	untilBump(bumpSwitchBack);          //Program won't begin until Back Switch is pressed
	startMotor(rightMotor, 127);        //Initialize straight motor speed
	startMotor(leftMotor, -127);
	untilBump(bumpSwitchFront);         //Go straight until Front Switch triggered
	startMotor(rightMotor, -100);       //Turning CCW direction so same, negative value
	startMotor(leftMotor, -100);




}
